name: Piper
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
    - "master"
 
jobs:
  piper:
    uses: "signavio/shared-workflows/.github/workflows/sig-piper-workflow.yml@v3.1.3"
    secrets: inherit
    with:
      extensibility-enabled: true
      runs-on: '["solinas-medium"]'
    permissions:
      contents: write
      id-token: write
      security-events: write
      actions: read